feat: base factory pattern with test + 0.5.5 refactor (#9)
* base factory pattern with test

* geyser base wip

* feat: geyser updateExample with connect

* fix: decode user_input to write properly

* fix: remove quotes in rust

* calling to itself

* updateExample

* fix: names from main changes

* fix: test

* fix: validate in the geyser contract with service manager

* fix: funded key not dpk

* transfer ownership, new workflow info

* migrate to wavs 0.5.5 with upgrade ability for factory pattern

* refactor(->base factory pr): 0.5.5 upgrade (#12)

* wavs 0.5.5 component migration from 0.4.0

* wip: "@wavs/solidity": "0.5.0-beta.10", working now

* rm calling telemetry, factory pattern finally worked

* update bindings to wavs world 0.5.1 from 0.4.1 leftovers

diff --git a/taskfile/env.yml b/taskfile/env.yml
--- a/taskfile/env.yml
+++ b/taskfile/env.yml
@@ -89,17 +89,19 @@ tasks:
   setup-avs-signing:
     desc: "Setup AVS signing keys for service"
     vars:
-      SERVICE_INDEX: '{{.SERVICE_INDEX | default "0"}}'
+      HD_INDEX: '{{.HD_INDEX | default "1"}}'
       DEFAULT_ENV_FILE: '{{.DEFAULT_ENV_FILE | default "infra/wavs-1/.env"}}'
     cmds:
       - |
-        SERVICE_ID=`curl -s http://localhost:8000/app | jq -r ".services[{{.SERVICE_INDEX}}].id"`
-        if [ -z "$SERVICE_ID" ] || [ "$SERVICE_ID" == "null" ]; then
-          echo "Error: SERVICE_ID is null or not found for index {{.SERVICE_INDEX}}." >&2
-          exit 1
-        fi
+        # SERVICE_ID=`curl -s http://localhost:8000/app | jq -r ".services[{{.SERVICE_INDEX}}].id"`
+        # if [ -z "$SERVICE_ID" ] || [ "$SERVICE_ID" == "null" ]; then
+        #   echo "Error: SERVICE_ID is null or not found for index {{.SERVICE_INDEX}}." >&2
+        #   exit 1
+        # fi
 
-        HD_INDEX=`curl -s http://localhost:8000/service-key/${SERVICE_ID} | jq -rc '.secp256k1.hd_index'`
+        # wavs 0.5.2 changed this where there are no longer service ids to get from the app.
+        # hardcoding for now :shrug: idk..
+        HD_INDEX={{.HD_INDEX}}
 
         source {{.DEFAULT_ENV_FILE}}
         export OPERATOR_PRIVATE_KEY=`cast wallet private-key --mnemonic "$WAVS_SUBMISSION_MNEMONIC" --mnemonic-index 0`
